// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team7843.subsystems;


import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import org.usfirst.frc.team7843.RobotMap;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.Servo;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Arm extends Subsystem {
    private final WPI_TalonSRX armMotor = RobotMap.armMotor;
    private final Servo armServo = RobotMap.armServo;

    @Override
    protected void initDefaultCommand(){}

    //Allows other files to edit servo position easier
    public void setServo(double position){
        this.armServo.set(position);
        // Range is from 0.0 (left) to 1.0 (right)
    }

    public void setArmSpeed(double speed){
        this.armMotor.set(speed);
        //Range is from -1.0 (CCW) to 1.0 (CW)
    }


}
