package org.usfirst.frc.team7843.subsystems;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

public class Drive extends Subsystem {
    // Set all variables for code
    private WPI_VictorSPX motor_FrontLeft;
    private WPI_VictorSPX motor_BackLeft;
    private WPI_VictorSPX motor_FrontRight;
    private WPI_VictorSPX motor_BackRight;
    private DifferentialDrive robotDrive;
    private SpeedControllerGroup m_left;
    private SpeedControllerGroup m_right;

    // Create Drive function; Holds all data for speed controllers & drive
    public Drive() {

        motor_FrontLeft = new WPI_VictorSPX(0);
        motor_BackLeft = new WPI_VictorSPX(1);
        
        motor_FrontRight = new WPI_VictorSPX(2);
        motor_BackRight = new WPI_VictorSPX(3);
        
        // Set the motors to a speed controller group
        m_left = new SpeedControllerGroup(motor_FrontLeft, motor_BackLeft);
        m_right = new SpeedControllerGroup(motor_FrontRight, motor_BackRight);

        // Inverts the left motors
        m_left.setInverted(true);


        // "robotDrive" is for variables relating to the drive
        // "m_left" & "m_right" are variables controlled for speed
        robotDrive = new DifferentialDrive(m_left, m_right);
        
        // Enable safety for the motors
        robotDrive.setSafetyEnabled(true);

        // Set maximum output speed for motors, generally cannot be more than 1.
        robotDrive.setMaxOutput(1.0);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

        /*
        *  DRIVE COMMAND
        */

        
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

